In [3]:
import csv
reader = csv.reader(open('tdoc.csv', 'r'))
docs = {}
for row in reader:
   k, v = row
   docs[k] = v

In [4]:
keys = list(docs.keys())
keys

['Document 1', 'Document 2', 'Document 3']

In [5]:
cons = []
for a in docs:
    cons.append(docs.get(a))
print(cons)

['This is the first document. It contains some words.', 'The second document is a bit longer and has different words.', 'The third document is short. Short documents can be concise.']


In [6]:
unique_terms = {term for doc in cons for term in doc.split()}
unique_terms

{'It',
 'Short',
 'The',
 'This',
 'a',
 'and',
 'be',
 'bit',
 'can',
 'concise.',
 'contains',
 'different',
 'document',
 'document.',
 'documents',
 'first',
 'has',
 'is',
 'longer',
 'second',
 'short.',
 'some',
 'the',
 'third',
 'words.'}

In [7]:
import pandas as pd
myDocs = pd.DataFrame(list(unique_terms))
myDocs.to_csv("uniqueTerm.csv",index = False)

In [8]:
# create a matrix for the document by using the unique term
doc_term_matrix = {}

# your code here
for term in unique_terms:
    doc_term_matrix[term] = []
    
    for doc in cons:
        if term in doc:
            doc_term_matrix[term].append(1)
        else: doc_term_matrix[term].append(0)

# display the result of the matrix
doc_term_matrix

{'document': [1, 1, 1],
 'Short': [0, 0, 1],
 'first': [1, 0, 0],
 'is': [1, 1, 1],
 'contains': [1, 0, 0],
 'be': [0, 0, 1],
 'the': [1, 0, 0],
 'can': [0, 0, 1],
 'different': [0, 1, 0],
 'a': [1, 1, 1],
 'document.': [1, 0, 0],
 'This': [1, 0, 0],
 'concise.': [0, 0, 1],
 'bit': [0, 1, 0],
 'It': [1, 0, 0],
 'third': [0, 0, 1],
 'short.': [0, 0, 1],
 'The': [0, 1, 1],
 'documents': [0, 0, 1],
 'has': [0, 1, 0],
 'and': [0, 1, 0],
 'words.': [1, 1, 0],
 'longer': [0, 1, 0],
 'some': [1, 0, 0],
 'second': [0, 1, 0]}

In [9]:
# import the numpy library if it doesn't work you need to install numpy
import numpy as np

docs_array = np.array(cons, dtype='object')

v1 = np.array(doc_term_matrix['some'])    
v2 = np.array(doc_term_matrix['first'])

print(v1)
print(v2)
print('-------')

# find the documents that have both terms from v1 and v2
v3 = v1 & v2

print(v3)

# display the content document from the result
search = [doc for doc in v3 * docs_array if doc]

print(search)

keys = set()

for a,v in docs.items():
    if v in search:
        keys.add(a)
print("Key value:",keys)

[1 0 0]
[1 0 0]
-------
[1 0 0]
['This is the first document. It contains some words.']
Key value: {'Document 1'}


In [10]:
# import the numpy library if it doesn't work you need to install numpy
import numpy as np

docs_array = np.array(cons, dtype='object')

v1 = np.array(doc_term_matrix['The'])    
v2 = np.array(doc_term_matrix['It'])

print(v1)
print(v2)
print('-------')

# find the documents that have both terms from v1 and v2
v3 = v1 | v2

print(v3)

# display the content document from the result
search = [doc for doc in v3 * docs_array if doc]

print(search)

keys = set()

for a,v in docs.items():
    if v in search:
        keys.add(a)
print("Key value:",keys)

[0 1 1]
[1 0 0]
-------
[1 1 1]
['This is the first document. It contains some words.', 'The second document is a bit longer and has different words.', 'The third document is short. Short documents can be concise.']
Key value: {'Document 3', 'Document 2', 'Document 1'}
